import type { Metadata } from "next";
import { Russo_One } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import ArticleCard from "./components/ArticleCard";

const russoRegular = Russo_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-russo"
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${russoRegular.className} antialiased`}
          >
          {children}
        </body>
    </html>
  );
}
